{
 "title": "HDG",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Temperaturen",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "hdg_value{id=~\"2200[01]\"}",
     "legendFormat": "{{desc1}}"
    }
   ]
  },
  {
   "title": "Temperaturen Kessel und Rücklauf",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "hdg_value{id=~\"22003|22022\"}",
     "legendFormat": "{{desc1}}"
    },
    {
     "expr": "hdg_value{id=~\"22004|22023\"}",
     "legendFormat": "{{desc1}}"
    }
   ]
  },
  {
   "title": "Materialmenge",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "hdg_value{id=~\"22005\"}",
     "legendFormat": "{{desc1}}"
    }
   ]
  },
  {
   "title": "Temperaturen Puffer 1",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "hdg_value{id=~\"2400[012]\"}",
     "legendFormat": "{{desc1}} {{id}}"
    }
   ]
  },
  {
   "title": "Betriebsstunden",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "hdg_value{id=~\"2201[12345]|2203[789]\"}",
     "legendFormat": "{{desc1}}"
    }
   ]
  },
  {
   "title": "Betriebsstunden pro Woche",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(hdg_value{id=~\"2201[12345]|2203[789]\"}[1w])",
     "legendFormat": "{{desc1}}"
    }
   ]
  },
  {
   "title": "Wärmeenergie",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": "hdg_value{id=~\"22069\"}*1000",
     "legendFormat": "{{desc1}}"
    }
   ]
  },
  {
   "title": "Wärmeenergie pro Woche",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": "increase(hdg_value{id=~\"22069\"}[7d])*1000",
     "legendFormat": "Wärmeenergie pro Woche"
    }
   ]
  },
  {
   "title": "Restsauerstoff",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "hdg_value{id=\"22002\"}",
     "legendFormat": "{{desc1}} Ist"
    },
    {
     "expr": "hdg_value{id=\"22050\"}",
     "legendFormat": "{{desc1}} Soll"
    }
   ]
  },
  {
   "title": "Wirkungsgrad",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "hdg_value{id=~\"22028\"}",
     "legendFormat": "{{desc1}}"
    }
   ]
  }
 ]
}