{
 "title": "HDG",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Temperaturen",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "hdg_value{id=~\"2200[01]|2605\"}",
     "legendFormat": "{{desc1}}"
    }
   ]
  },
  {
   "title": "Temperaturen Kessel und Rücklauf",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "hdg_value{id=~\"22003|22022\"}",
     "legendFormat": "{{desc1}}"
    },
    {
     "expr": "hdg_value{id=~\"22004\"}",
     "legendFormat": "{{desc1}}"
    },
    {
     "expr": "hdg_value{id=~\"22023\"}",
     "legendFormat": "{{desc1}} Soll"
    }
   ]
  },
  {
   "title": "Materialmenge",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "hdg_value{id=~\"22005|2615|2616\"}",
     "legendFormat": "{{desc1}}"
    }
   ]
  },
  {
   "title": "Puffer",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "hdg_value{id=~\"2400[012]\"}",
     "legendFormat": "{{desc1}}"
    },
    {
     "expr": "hdg_value{id=~\"24004\"}",
     "legendFormat": "{{desc1}} (oben)"
    },
    {
     "expr": "hdg_value{id=~\"24006\"}",
     "legendFormat": "{{desc1}} (unten)"
    }
   ]
  },
  {
   "title": "Restsauerstoff",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "hdg_value{id=\"22002\"}",
     "legendFormat": "{{desc1}} Ist"
    },
    {
     "expr": "hdg_value{id=\"22050\"}",
     "legendFormat": "{{desc1}} Soll"
    }
   ]
  },
  {
   "title": "Brauchwasser",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "hdg_value{id=~\"2800[012]\"}",
     "legendFormat": "{{desc1}}"
    },
    {
     "expr": "hdg_value{id=~\"802[12]\"}",
     "legendFormat": "{{desc1}}"
    }
   ]
  },
  {
   "title": "Luftklappen",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "hdg_value{id=~\"2200[89]\"}",
     "legendFormat": "{{desc1}}"
    },
    {
     "expr": "hdg_value{id=~\"22019|22033\"}",
     "legendFormat": "{{desc1}} (Soll)"
    }
   ]
  },
  {
   "title": "Kesselstatus",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "hdg_value{id=\"22010\"} == 16 >bool 0",
     "legendFormat": "Ausbrennen"
    },
    {
     "expr": "(hdg_value{id=\"22010\"} == 0 >bool 0) + 1",
     "legendFormat": "Störung"
    },
    {
     "expr": "hdg_value{id=\"22010\"} == 18 >bool 0",
     "legendFormat": "Restwärme"
    },
    {
     "expr": "(hdg_value{id=\"22010\"} == 8 >bool 0) + 0.5",
     "legendFormat": "Automatik"
    },
    {
     "expr": "hdg_value{id=\"22010\"} == 2 >bool 0",
     "legendFormat": "Entaschen"
    },
    {
     "expr": "hdg_value{id=\"22010\"} == 3 >bool 0",
     "legendFormat": "Vorbelüften"
    },
    {
     "expr": "hdg_value{id=\"22010\"} == 4 >bool 0",
     "legendFormat": "Füllen"
    },
    {
     "expr": "hdg_value{id=\"22010\"} == 5 >bool 0",
     "legendFormat": "Anzünden"
    },
    {
     "expr": "(hdg_value{id=\"22010\"} == 1 >bool 0) - 0.5",
     "legendFormat": "Bereit"
    },
    {
     "expr": "hdg_value{id=\"22010\"} == 7 >bool 0",
     "legendFormat": "Anheizen"
    },
    {
     "expr": "hdg_value{id=\"22010\"} == 6 >bool 0",
     "legendFormat": "Anzünden kühlen"
    }
   ]
  },
  {
   "title": "Stunden im Zustand \"Automatik\" im gewählten Zeitfenster",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg_over_time((hdg_value{desc1=\"Kesselstatus\"} ==bool 8)[$__range:1m]) * $__range_s / 3600",
     "legendFormat": "Stunden im Zustand \"Automatik\""
    }
   ]
  },
  {
   "title": "Betriebsstunden",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "hdg_value{id=~\"2201[12345]|2203[789]\"}",
     "legendFormat": "{{desc1}}"
    }
   ]
  },
  {
   "title": "Betriebsstunden pro Woche",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(hdg_value{id=~\"2201[12345]|2203[789]\"}[1w])",
     "legendFormat": "{{desc1}}"
    }
   ]
  },
  {
   "title": "Wärmeenergie",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": "hdg_value{id=~\"22069\"}*1000",
     "legendFormat": "{{desc1}}"
    }
   ]
  },
  {
   "title": "Wärmeenergie pro Woche",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": "increase(hdg_value{id=~\"22069\"}[7d])*1000",
     "legendFormat": "Wärmeenergie pro Woche"
    },
    {
     "expr": "hdg_value{id=\"20000\"}",
     "legendFormat": "{{desc1}}"
    }
   ]
  },
  {
   "title": "Wirkungsgrad",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "hdg_value{id=~\"22028\"}",
     "legendFormat": "{{desc1}}"
    }
   ]
  }
 ]
}